### ISSUE TITLE
Running gets stuck[Bug]

### ISSUE THREAD

**Issue by Utfigyii** [armory3d/logic_pack#16]
when running and letting go the "directional key"(i.e. w) and letting the running key go, it keeps running until the "directional key" is pressed again.

**Comment by yboettcher** [comment]
At least for me, this **only** affects the shift key. If I use Control for running, everything is fine.
I experience this behaviour even when there is no node using the shift key, so I would guess the problem is somewhere in the input handling code.

**Comment by luboslenco** [comment]
Linky to https://github.com/armory3d/armory/issues/950 & https://github.com/armory3d/armory/issues/891.
