### ISSUE TITLE
'Path not found' error on windows

### ISSUE THREAD

**Issue by smithian123** [armory3d/logic_pack#21]
Hi,
I have placed the unpacked logic_pack files in a directory named "libraries" in the same directory as my .blend file and it doesn't work. The error message is;
-------
Read blend: C:\Users\qwuff\Documents\blender\2018\armory\tutorials\turntable.blend 
path not found
-------

I'm using windows 10, Blender 2.79b and Armory 0.5 for win64

Thanks,
Ian

**Comment by luboslenco** [comment]
Hi, should be good in latest 0.6 builds!
