### ISSUE TITLE
Build Failed On Timer Node (and others)

### ISSUE THREAD

**Issue by Gedankenexper1ment** [armory3d/logic_pack#23]
I'm getting build failed check console when trying to run with the timer node. 
Console:
`C:\[filepath]/logicnode/TimerNode.hx:70 characters 5-14 : unknown identifier : runOutput`
along with a number of other errors like this in succession. I'm using 2.79 and the armory build posted on itch.io.

**Comment by luboslenco** [comment]
Hello,

- If you are using the 0.5 build, get the logic_pack 0.5 [here](https://github.com/armory3d/logic_pack/releases)
- Or you can update Armory to the git version using the [updater](https://armory3d.org/manual/#/dev/gitversion?id=armory-updater) to make it work

Basically the latest version of this repository works with the latest version of Armory. Sorry about the insufficient instructions, will fix that.

**Comment by Gedankenexper1ment** [comment]
That would make sense, thank you for your help.
